### ISSUE TITLE
Improve layout, UIUIX, Look n Feel

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwlcon2024#26]
Placeholder for the updates for the UIUX.

@alexiswl creating this one to track all requirements in a single place. @Fienne, you can look at just this one whenever you have time later :+1: and it should contain links to the open issues that are related to design, UIUX, etc.

- [x] improve the general layout (alignment, consistency, typography, colors, ...)
  - I think it might be nice if we are able to offer:
    - [ ] dark theme
    - [ ] good accessibility (including but not only color-blindness)
- [x] mobile friendly, small https://github.com/common-workflow-language/cwlcon2024/issues/24
- [x] modify how location & date are displayed (that issue will be used for other topics) https://github.com/common-workflow-language/cwlcon2024/issues/18
- [ ] we need to make the website look more fun https://github.com/common-workflow-language/cwlcon2024/issues/29
